theme: jekyll-theme-minimal
title: '1st Workshop on Long-term Deployments in the Wild (LoWi): Perception and Learning'
github:
  is_user_page: false
  is_project_page: false
logo: /images/logo_LoWi.png
